name: Java CI Pipeline

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Замени на нужную версию JDK
          distribution: 'temurin'

      # Шаг 3: Сборка приложения с помощью Maven
      - name: Build with Maven
        run: mvn clean install

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: mvn test
